### PR TITLE
Add flags to PowerShell 4 install for no UI and no restart

### PR DESCRIPTION
**Pull request by zl4bv**

### CODE REVIEW

**Comment by NimishaS** [comment]
Hello @zl4bv , we have removed `/norestart` as we need to reboot PC after powershell installation. However `/quiet` was removed by mistake, which will be added soon once PR https://github.com/chef-windows/powershell/pull/32 gets merged

**Comment by zl4bv** [comment]
Hi @NimishaS , so if we rely on Windows Update Standalone Installer to perform its own reboot does that mean it is no longer necessary to include the reboot handler on line 40?

```ruby
include_recipe 'powershell::windows_reboot' if node['powershell']['installation_reboot_mode'] == 'immediate_reboot' && powershell_version < 4
```

**Comment by NimishaS** [comment]
@zl4bv , we are not relying on Windows Update Standalone Installer to perform reboot. What I experienced was that Windows Update Standalone Installer didn't prompt for reboot also because of `/quiet`.
Reboot happens because of line #40 only. i.e.
```ruby
include_recipe 'powershell::windows_reboot' if node['powershell']['installation_reboot_mode'] == 'immediate_reboot' && powershell_version < 4
```

**Comment by NimishaS** [comment]
@zl4bv , Reboot fixes have been merged in the master branch. You can use it now. 
We can close this PR if your requirements are fulfilled.

**Comment by zl4bv** [comment]
Thanks for your help @NimishaS - yes my requirements are fulfilled.

**Pull request closed without merging**
